from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_results(object):
    def __init__(self, ekg_result, spq2a_result, resp_ecq_result, ni_bp_result):
        self.ekg_result = ekg_result
        self.spq2a_result = spq2a_result
        self.resp_ecq_result = resp_ecq_result
        self.ni_bp_result = ni_bp_result

    def setupUi(self, results):
        results.setObjectName("results")
        results.resize(465, 372)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        results.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(results)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 14, 59, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 82, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 128, 123, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 170, 65, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it())
        self.pushButton.setGeometry(QtCore.QRect(100, 270, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setItalic(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 20, 71, 21))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(100, 60, 81, 21))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(130, 130, 81, 21))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(70, 170, 91, 21))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        results.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(results)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 465, 26))
        self.menubar.setObjectName("menubar")
        results.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(results)
        self.statusbar.setObjectName("statusbar")
        results.setStatusBar(self.statusbar)

        self.retranslateUi(results)
        QtCore.QMetaObject.connectSlotsByName(results)

    def retranslateUi(self, results):
        _translate = QtCore.QCoreApplication.translate
        results.setWindowTitle(_translate("results", "Results"))
        self.label.setText(_translate("results", "EKG:"))
        self.label_2.setText(_translate("results", "SPQ2A:"))
        self.label_3.setText(_translate("results", "RESP ECG:"))
        self.label_5.setText(_translate("results", "NIBP:"))
        self.pushButton.setText(_translate("results", "VIEW"))


    def press_it(self):
        self.label_4.setText(self.ekg_result)
        self.label_6.setText(self.spq2a_result)
        self.label_7.setText(self.resp_ecq_result)
        self.label_8.setText(self.ni_bp_result)
